---
- hosts: all
  become: true
  tasks:
    - name: Install required system packages
      package:
        name:
          - default-jre
        state: latest
        update_cache: true

    - name: Copy jar
      copy:
        src: ../target/ansible-playground-1.0-SNAPSHOT.jar
        dest: /usr/local/bin/ansible-playground.jar

    - name: Run jar
      command: java -jar /usr/local/bin/ansible-playground.jar
      register: java_output

    - debug:
        msg: "{{ java_output.stdout }}"
